[book]
title = "Zizq Rust Client"
authors = ["Chris Corbyn"]
description = "Zizq Rust Client Documentation — The lightweight job queue server"
language = "en"
src = "src"

[build]
build-dir = "../target/docs"

[output.html]
site-url = "/docs/clients/rust/"
additional-css = ["src/zizq_docs.css"]
default-theme = "light"
preferred-dark-theme = "light"

[output.html.print]
enable = false
